language: c
compiler: clang
git:
  submodules: false
dist: trusty
addons:
  apt:
    packages:
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
script:
  - cmake . -B.core && cmake --build .core
  - git submodule update --init
  - cmake . -B.demos && cmake --build .demos
