language: c
compiler: clang
# submodules: false
dist: trusty
addons:
  apt:
    packages:
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
script:
  - cmake . -B.debug
  - cmake --build .debug
