language: c

compiler: clang

git:
  submodules: false

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev

script:
  - cmake . -B.core && cmake --build .core
  - git submodule update --init
  - cmake . -B.demos && cmake --build .demos
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd extras/macos            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake -H. -B_build -GXcode ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake --build _build       ; fi
  