language: c
compiler: clang
dist: trusty
addons:
  apt:
    packages:
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      - mesa-vulkan-drivers 
      - vulkan-utils
script:
  - cmake . -Bbuild
  - cmake --build build
