language: c
addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.9
script:
  - export CC=clang CXX=clang++
  - cmake test -Bbuild
  - cmake --build build
